### ISSUE TITLE
iamadamdev-bypass-paywalls-issue

### ISSUE THREAD

**Issue by sollygit** [laur89/awesome-stars#1]
Hi,
I saw you have contributed to bypass-paywalls extention before.
I couldn't find a way to raise an issue on this repo because it's only for contributers (that's why I am contacting you :-) )

When the extension is enabled I get this following message while trying to access either 

https://www.haaretz.co.il 
https://www.haaretz.com

When the extension is disabled, or when those sites are excluded in the options, they can be accessed normally.

Error 403 Forbidden
Forbidden
Error 54113
Details: cache-akl10327-AKL 1678485038 1646396862

Varnish cache server

Same issue raised and fixed in the past:
https://github.com/iamadamdev/bypass-paywalls-chrome/issues/1004

1. Could you open a new issue please?
2. Maybe you can find the issue and apply a fix?
3. Is there any temporary solution/fix I can apply until the next release?

Thank you,
Solly.

**Comment by arnonsha** [comment]
For me as well...

**Comment by osh123** [comment]
Same for https://www.themarker.com/

**Comment by SirAppSec** [comment]
Any update on this?

**Comment by pxp5717** [comment]
still waiting for the update

**Comment by guysoft** [comment]
Same for me, disabling makes it work again, any way to help?

![Screenshot_20230921_211747](https://github.com/laur89/awesome-stars/assets/325670/3d2f043d-f0ca-44f3-9445-111dc2dabd01)


Error 403 Forbidden

Forbidden
Error 54113

Details: cache-fra-etou8220073-FRA 1695320237 2112756609

Varnish cache server

**Comment by guysoft** [comment]
Was this fixed?

**Comment by sollygit** [comment]
Yes

**Comment by yeyelol9** [comment]
Same issue

**Comment by guysoft** [comment]
Does not work here still
